# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'TodoNote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoNote
  pod "KRProgressHUD"
  pod 'UIDeviceIdentifier'
  pod 'UITextView+Placeholder'

  # for Firebase
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'FirebasePerformance'

  # for script
  pod 'R.swift'
  pod 'SwiftFormat/CLI', '~> 0.49'
  pod 'LicensePlist'
  pod 'LicensePlistViewController'

  target 'TodoNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoNoteUITests' do
    # Pods for testing
  end

end
